title: Mak's sit
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  place for stuff
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: makasaito

